services:
  mongo:
    image: mongo:6.0.11
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    networks:
      - voltron
    restart: always

  redis:
    image: redis:7.2.1
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    networks:
      - voltron
    restart: always

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.37.0
    command: server --config=/config/conf.yaml
    volumes:
      - ./cerbos/conf.yaml:/config/conf.yaml
      - ./cerbos/policies:/config/policies
    ports:
      - 127.0.0.1:${CERBOS_HTTP_PORT}:3592
      - 127.0.0.1:${CERBOS_GRPC_PORT}:3593
    networks:
      - voltron
    restart: always

networks:
  voltron:
