services:
  mongo:
    image: mongo:6.0.11
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    networks:
      - voltron
    restart: always

  redis:
    image: redis:7.2.1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./redis/conf:/usr/local/etc/redis/redis.conf
    networks:
      - voltron
    restart: always

  cerbos:
    image: ghcr.io/cerbos/cerbos:0.30.0
    command: server --config=/config/conf.yaml
    ports:
      - "${CERBOS_HTTP_PORT}:3592"
      - "${CERBOS_GRPC_PORT}:3593"
    volumes:
      - ./cerbos/conf.yaml:/config/conf.yaml
      - ./cerbos/policies:/config/policies
    networks:
      - voltron
    restart: always

networks:
  voltron:
    driver:
